title: |
  <div style="font-size:18px; line-height:1.5; color:#000; text-align:center;">
    <img src='/image.jpeg' width='130' style='border-radius:50%; margin-bottom:10px'><br>
    Dhanhanjay Pachori<br>
    Undergraduate Student, Indian Institute of Information Technology, Nagpur<br>
    <a href='mailto:bt22ece024@iiitn.ac.in'>bt22ece024@iiitn.ac.in</a><br>
    <a href='https://scholar.google.com/citations?user=MUerymUAAAAJ&hl=en'>Google Scholar</a> | 
    <a href='https://linkedin.com/in/dhanhanjay-pachori/'>LinkedIn</a> | 
    <a href='https://orcid.org/0009-0004-9748-604X'>ORCID</a>
  </div>
